image: gitlab.i22.de:5001/docker/i22-ubuntu:20.04

before_script:
  - gem install bundler -v 2.2.15
  - bundle install -j $(nproc) --path vendor/ruby

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby

lint:
  script:
    - bundle exec rubocop

test:
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - coverage
