AllCops:
  Exclude:
    - '*.gemspec'
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'vendor/**/*'
